
# ==================================================
# Data Utils
# ==================================================

data_utils:
  # raw_data_path: '/ABS/PATH/brazillian-ecommerce-analytics/data/raw'
  raw_data_path: '/Users/palmmy/pyFreelance/brazillian-ecommerce-analytics/data/raw'
  kaggle_dataset: 'olistbr/brazilian-ecommerce'


